name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ' 3.11'  # adjust if needed

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-html
      # 4. Run tests with pytest
      - name: Run tests
        run: |
          pytest ./tests --html=rapport.html --self-contained-html
         

  # 5. Generate HTML report
     # - name: Generate report
      #  run: |
      #    python generate_report.py  # votre script qui crÃ©e rapport.html

      # 6. Upload report as artifact
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: rapport-html
          path: rapport.html

  deploy:
    needs: test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: echo "deployement started"
notify:
  name: Email Notification
  runs-on: ubuntu-latest
  needs:
    - build-and-test
    - deploy
  if: always()

  steps:
    - name: Download test report artifact
      uses: actions/download-artifact@v4
      with:
        name: test-report
        path: ./report

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ zakraouiasma2019@gmail.com  }}
        password: ${{ uyxz claz gfmc sxdw }}
        subject: >
          [${{ github.repository }}] Pipeline ${{ job.status }}
        to: ${{ zakraouiasma2019@gmail.com }}
        from: GitHub Actions <${{ zakraouiasma2019@gmail.com  }}>
        body: |
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Status: ${{ job.status }}

          Commit SHA: ${{ github.sha }}
          Branch: ${{ github.ref_name }}

          Build & Test: ${{ needs.build-and-test.result }}
          Deploy: ${{ needs.deploy.result }}
        attachments: ./report/rapport.html
